# Generated by Django 5.2.16 on 2026-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='username'),
        ),
    ]
