# Generated by Django 5.2.16 on 2026-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member.', max_length=150, verbose_name='Name')),
                ('role', models.CharField(help_text='Corporate title or professional role.', max_length=150, verbose_name='Role/Designation')),
                ('image', models.ImageField(blank=True, help_text='Upload a high-quality portrait image. If empty, the default placeholder asset will be used.', null=True, upload_to='team/', verbose_name='Profile Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Used to order items in the UI. Lower values appear first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily hide this member from the public layout.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
