# Generated by Django 5.2.16 on 2026-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('role', models.CharField(max_length=150, verbose_name='Professional Title / Role')),
                ('location', models.CharField(default='Global', max_length=100, verbose_name='City / Region')),
                ('quote', models.TextField(verbose_name='Testimonial Quote')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Star Rating (1-5)')),
                ('category', models.CharField(choices=[('entrepreneur', 'Entrepreneurs'), ('portfolio_manager', 'Portfolio Managers'), ('saver', 'Long-term Savers'), ('institutional', 'Institutional Investors')], default='entrepreneur', max_length=50, verbose_name='Category')),
                ('avatar_image', models.CharField(blank=True, default='avatar_emily.png', max_length=255, verbose_name='Avatar Asset Name or URL')),
                ('is_verified_linkedin', models.BooleanField(default=True, verbose_name='Verified via LinkedIn')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', verbose_name='LinkedIn Profile URL')),
                ('pos_x', models.FloatField(default=30.0, help_text='X percentage coordinate (0-100) on global map grid', verbose_name='Map X Position (%)')),
                ('pos_y', models.FloatField(default=40.0, help_text='Y percentage coordinate (0-100) on global map grid', verbose_name='Map Y Position (%)')),
                ('badge_theme', models.CharField(choices=[('cyan', 'Cyan Glow'), ('emerald', 'Emerald Glow'), ('amber', 'Amber/Gold Glow'), ('violet', 'Violet Glow')], default='cyan', max_length=30, verbose_name='Glow Theme')),
                ('card_type', models.CharField(choices=[('bubble', 'Glowing Organic Bubble'), ('glass_card', 'Sleek Dark Glass Card'), ('node_only', 'Compact Avatar Node')], default='bubble', max_length=30, verbose_name='Display Card Style')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-rating', 'name'],
            },
        ),
    ]
