# Generated by Django 5.2.16 on 2026-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/', verbose_name='Uploaded Avatar Photo'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Avatar Asset Name or URL'),
        ),
    ]
