# Generated by Django 5.2.16 on 2026-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_testimonial_avatar_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_key', models.CharField(db_index=True, help_text='Unique 10-character alphanumeric tracking key (e.g., GT7K4M9P2X).', max_length=10, unique=True, verbose_name='Reference Key')),
                ('client_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('service', models.CharField(choices=[('financial_planning', 'Comprehensive Financial Planning'), ('investment', 'Investment & Multi-Asset Portfolio Strategy'), ('fixed_deposit', 'Fixed Deposit & High-Yield Preservation'), ('wealth_management', 'Private Wealth Management & Family Office'), ('retirement', 'Retirement & Legacy Structuring'), ('tax_planning', 'Tax Optimization & Fiscal Structuring'), ('portfolio_review', 'Institutional Portfolio Diagnostic & Health Check'), ('general', 'General Advisory & Wealth Strategy'), ('other', 'Bespoke Executive Financial Advisory')], default='financial_planning', max_length=50, verbose_name='Consultation Service')),
                ('duration_minutes', models.PositiveIntegerField(choices=[(30, '30 Minutes — Focused Consultation'), (45, '45 Minutes — Strategic Consultation'), (60, '60 Minutes — Comprehensive Consultation')], default=45, verbose_name='Duration (Minutes)')),
                ('consultation_date', models.DateField(verbose_name='Consultation Date')),
                ('consultation_time', models.TimeField(verbose_name='Consultation Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Consultation End Time')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='Subject / Purpose')),
                ('message', models.TextField(blank=True, default='', verbose_name='Requirements / Message')),
                ('preferred_comm', models.CharField(choices=[('video_call', 'Secure Video Conference (Zoom / Google Meet)'), ('in_person', 'In-Person Executive Desk (Main Office)'), ('phone', 'Direct Private Phone Call'), ('email', 'Written Strategic Advisory Briefing')], default='video_call', max_length=30, verbose_name='Preferred Communication Method')),
                ('status', models.CharField(choices=[('received', 'Booking Received'), ('under_review', 'Pending Confirmation / Under Review'), ('confirmed', 'Confirmed'), ('paid', 'Paid / Confirmed'), ('payment_pending', 'Payment Pending'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=30, verbose_name='Booking Status')),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Received'), ('waived', 'Complimentary / Executive Waiver'), ('refunded', 'Refunded')], default='pending', max_length=30, verbose_name='Payment Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Advisor / Admin Internal Notes')),
                ('previous_date', models.DateField(blank=True, null=True, verbose_name='Previous Consultation Date')),
                ('previous_time', models.TimeField(blank=True, null=True, verbose_name='Previous Consultation Time')),
                ('rescheduled_reason', models.TextField(blank=True, default='', verbose_name='Rescheduling Reason / Note')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-consultation_date', '-consultation_time', '-created_at'],
            },
        ),
    ]
