# Generated by Django 5.2.16 on 2026-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_consultationbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Publication Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='trust_signals/media_mentions/', verbose_name='Logo Image')),
                ('link', models.URLField(blank=True, default='', verbose_name='Article Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Mention',
                'verbose_name_plural': 'Media Mentions',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Partner Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='trust_signals/partners/', verbose_name='Partner Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner Integration',
                'verbose_name_plural': 'Partner Integrations',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
