# Generated by Django 5.2.16 on 2026-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_consultationbooking_billing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Backup File Name')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('file_size_kb', models.FloatField(default=0.0, verbose_name='File Size (KB)')),
                ('trigger_event', models.CharField(default='Admin Panel Operation', max_length=255, verbose_name='Trigger Event')),
                ('is_automated', models.BooleanField(default=True, verbose_name='Automated Snapshot')),
                ('status', models.CharField(default='success', max_length=50, verbose_name='Backup Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Automated Database Backup',
                'verbose_name_plural': 'Automated Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminSaaSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='GreenTree FD Executive Admin Panel', max_length=200, verbose_name='Service Name')),
                ('client_name', models.CharField(default='Sabin Balan (Founder, GreenTree FD)', max_length=200, verbose_name='Client Name & Title')),
                ('client_email', models.EmailField(default='sabin@greentreefd.com', max_length=254, verbose_name='Client Billing Email')),
                ('provider_credits', models.CharField(default='VintushTech & KPRegTech', max_length=255, verbose_name='Provider Credits')),
                ('is_free_trial', models.BooleanField(default=True, verbose_name='Is Free Trial Active')),
                ('trial_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Trial Start Date')),
                ('trial_duration_days', models.PositiveIntegerField(default=90, verbose_name='Trial Duration (Days)')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Trial End Date')),
                ('subscription_status', models.CharField(choices=[('active_trial', 'Active 3-Month Free Trial'), ('active_paid', 'Active Paid Subscription'), ('grace_period', 'Grace Period Notice'), ('locked_expired', 'Access Expired & Locked')], default='active_trial', max_length=50, verbose_name='Subscription Status')),
                ('current_plan', models.CharField(choices=[('trial_3_months', '3 Months Free Trial (Complimentary)'), ('1_month', '1 Month Standard Plan ($49 / Rs. 3,999)'), ('3_months', '3 Months Quarterly Plan ($129 / Rs. 9,999)'), ('6_months', '6 Months Semi-Annual Plan ($229 / Rs. 17,999)'), ('1_year', '1 Year Enterprise Annual Plan ($399 / Rs. 29,999)')], default='trial_3_months', max_length=50, verbose_name='Active Plan')),
                ('paid_until', models.DateTimeField(blank=True, null=True, verbose_name='Access Valid Until')),
                ('license_key', models.CharField(blank=True, default='', max_length=150, verbose_name='Active License Key')),
                ('is_locked', models.BooleanField(default=False, help_text='Check to immediately lock the admin panel.', verbose_name='Manually Lock Admin Panel')),
                ('notes', models.TextField(blank=True, default='Initial 3-month free trial granted by VintushTech & KPRegTech.', verbose_name='License / Audit Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SaaS Subscription & License',
                'verbose_name_plural': 'SaaS Subscriptions & Licenses',
            },
        ),
        migrations.AlterField(
            model_name='consultationbooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid / Payment Due'), ('paid', 'Paid / Completed'), ('waived', 'Complimentary / Fee Waived'), ('pending', 'Payment Processing / Pending Verification'), ('refunded', 'Refunded')], default='unpaid', max_length=30, verbose_name='Payment Status'),
        ),
    ]
