# Generated by Django 5.0.0 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navfooter', '0002_populate_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image_url', models.URLField(blank=True, default='', help_text='Provide an external image URL to use as the navbar logo (e.g. https://example.com/logo.png).', max_length=500, verbose_name='Logo External URL')),
                ('logo_image_file', models.ImageField(blank=True, help_text='Upload a local image file to use as the navbar logo. If both file and URL are specified, the uploaded file takes precedence.', null=True, upload_to='navbar_logos/', verbose_name='Logo Local File')),
            ],
            options={
                'verbose_name': 'Navbar Settings',
                'verbose_name_plural': 'Navbar Settings',
            },
        ),
    ]
