# Generated by Django 5.0.0 on 2026-07-24

from django.db import migrations


def populate_navbar_settings(apps, schema_editor):
    NavbarSettings = apps.get_model('navfooter', 'NavbarSettings')
    if not NavbarSettings.objects.exists():
        NavbarSettings.objects.create(
            logo_image_url="",
            logo_image_file=None
        )


def depopulate_navbar_settings(apps, schema_editor):
    NavbarSettings = apps.get_model('navfooter', 'NavbarSettings')
    NavbarSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navfooter', '0003_navbarsettings'),
    ]

    operations = [
        migrations.RunPython(populate_navbar_settings, depopulate_navbar_settings),
    ]
